### ISSUE TITLE
Missing outer describe in some of tests

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-utils#100]
Missing outer describe makes test report less readable.

Eg:
- https://github.com/ckeditor/ckeditor5-utils/blob/master/tests/config.js
- https://github.com/ckeditor/ckeditor5-utils/blob/master/tests/emittermixin.js
- https://github.com/ckeditor/ckeditor5-utils/blob/master/tests/log.js

(could be more)

Besides that some of tests are unnecessarily wrapped by `describe( 'utils', () => { } ); `. Eg:
- https://github.com/ckeditor/ckeditor5-utils/blob/master/tests/spy.js
- https://github.com/ckeditor/ckeditor5-utils/blob/master/tests/nth.js

(could be more)

**Comment by Reinmar** [comment]
I can't see any `/\nit\(/` occurrences in our code so I think we're mostly fine. If we'll ever stumble upon some poorly described tests, we should simply fix them as we go.
