### ISSUE TITLE
Export each util separately

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-utils#12]
I should be able to do:
```
import { count } from '/ckeditor5/utils/utils.js';
```
Instead of:
```
import utils from '/ckeditor5/utils/utils.js';
const count = utils.count;
```

**Comment by Reinmar** [comment]
I'm actually thinking about implementing each util in a separate file. We could get rid of the file named `util.js` which looks funny in ` ckeditor5-utils` package.

Another argument for splitting utils will be that we'll be adding more and more functions to `util.js` and at some point we may end up with one huge file, like in CKE4. Module per function, like it's done by lodash, keeps things short and neat.

**Comment by pjasiun** [comment]
If you found it reasonable you can group these utils in folders like `dom` utils are grouped.

**Comment by oskarwrobel** [comment]
Thanks, I'll consider it.

**Comment by Reinmar** [comment]
How would we name it? `misc/`? Then we'll have to answer the question what falls into miscellaneous and what not :P.

**Comment by pjasiun** [comment]
We have a proud tradition of creating `utils` inside `utils` :D

But seriously, there is a  big group of utils which helps us dealing with collections (arrays, maps and editable). We could have them in one folder (together with a `diff` util) and the rest (`spy`, `uid` and `mix`) could be directly in the main directory. The problem is how to call such folder, since we already have `collection` util which is something different.

BTW: who use `spy` util, and why not sinon?

I do not think we should have a folder for miscellaneous utils since the whole repository is for it :P

**Comment by fredck** [comment]
Sounds unclear for me. I would just KISS and leave things at the root so we don't waste much more time talking about it.
