### ISSUE TITLE
Move ViewCollection.bind() to utils.Collection

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-utils#125]
Since it's a very useful feature to bind two collections, especially if you can do custom mapping, it should be moved to the `utils.Collection` to let users bind any collections, not only `ViewCollection`. 

Note that you can bind any observable variable, but not any observable collection, what is inconsistent.

The problem is that the binding checks if the parameter is the instance of `View` to check if it should be used or if the parameter is a creator function (https://github.com/ckeditor/ckeditor5-ui/blob/6b7fd4adfe6ee99fbdf84bfc4940f10ed78493b8/src/viewcollection.js#L227-L246). To solve it we could split the `as` function to separate function, what would make the code simpler and less magic:

```js
collection1.bindTo( collection2 ).byWrappingInto( MyViewClass );
collection1.bindTo( collection2 ).using( ( object ) => object.propery );
```

Note that in the future we might introduce another popular mapping helper, like for the last line from the example above:

```
collection1.bindTo( collection2 ).withProperty( 'property' );
```

**Comment by oleq** [comment]
It's probably more a matter of

```
collection1.bindTo( collection2 ).using( ( object ) => object.propery );
```

where for UI, it would be 

```
collection1.bindTo( collection2 ).using( viewFactoryInstance );
```

Current [implementation](https://github.com/ckeditor/ckeditor5-ui/blob/t/152/src/viewcollection.js#L218-L266) is straightforward. I think it's an easy thing to do.

**Comment by oleq** [comment]
I'm not sure what's the purpose of `byWrappingInto`. For me there are 2 real use–cases:
1. Binding a property like
  ```
collection1.bindTo( collection2 ).using( ( object ) => object.propery );
```
2. Binging as a factory i.e.
```
collection1.bindTo( collection2 ).using( ( object ) => new AnotherClass( object ) );
```
   which as good as
```
collection1.bindTo( collection2 ).using( AnotherClass );
```

Is there anything more than that?

**Comment by pjasiun** [comment]
For me that's fine.

**Comment by pjasiun** [comment]
By the way: it would be nice to have the two-way binding of collections. Will it work out of the box, or we need a separate ticket for it?

**Comment by oleq** [comment]
@pjasiun I'm not sure what outcome would you expect when the binding is used as a factory. 

But anyway, we considered it in the UI https://github.com/ckeditor/ckeditor5-ui/issues/110.
