### ISSUE TITLE
Config – an easy way to load the default config

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-utils#126]
As posted here - https://github.com/ckeditor/ckeditor5-core/pull/72#issuecomment-283611499 - we need to introduce default parameters for `Config`.

It is required for support `Editor.build` property (https://github.com/ckeditor/ckeditor5-core/issues/67).

**Comment by Reinmar** [comment]
To be more precise – we need an easy option to pass the default config before loading a user config.
