### ISSUE TITLE
`first` util to get the first item from the generator

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-utils#130]
It's basically `generator.next().value;`, but:

```js
first( doc.selection.getSelectedBlocks() );
```
seems to be more readlable them:

```js
doc.selection.getSelectedBlocks().next().value;
```

I know we have `nth`, but it's a common case when you wants to get the first value and we could have a dedicated method for it.

**Comment by Reinmar** [comment]
We've got `nth()` already, but I also see that `first()` is being the most popular use case in the normal code. `nth()` is mostly used in the tests.

**Comment by ma2ciek** [comment]
But similarly to `nth()` implementation the implementation of `first()` shouldn't change the iterator, right? (Like `iterator.next().value` does)

**Comment by pjasiun** [comment]
What do you mean? `nth()` do change the iterator.

**Comment by ma2ciek** [comment]
I checked it and the `nth( index, iterable )` function even finishes the iterator no matter what the `index` is, becaus every `for of` loop finishes the iterator. So maybe the `first( iterator )` function should run inside just nth( 0, iterator ) :D

**Comment by Reinmar** [comment]
Interesting... I'd love `first()` to work like `shift()` because subsequent `first()` calls may be a usecase one day. But `nth()` can read the entire iterable. It's even better if `nth()` reads the entire iterable, because then you'd have a better chance to notice that something went wrong (if you didn't know that it consumes the items)

**Comment by ma2ciek** [comment]
Ok. So the PR for the `first()` is ready and the missing parts are fixed. It works similar to the `shift()` for now. I'll report an issue for the `nth()` function improvement.

**Comment by Reinmar** [comment]
As I commented in #130 I find my previous proposal totally wrong now. I take it back :P

**Comment by pjasiun** [comment]
If we want to pop the first value multiple times maybe we should have a better name, like `pop` or `head` (note that lodash use `head` and `first` is the alias for it https://lodash.com/docs/4.17.4#head)?

**Comment by Reinmar** [comment]
`pop()` means taking the last item. And I like `first()` more than `head()`. But I'm fine with both.
