### ISSUE TITLE
'nth' function should consume the given iterable object.

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-utils#136]
As mentioned https://github.com/ckeditor/ckeditor5-utils/issues/130#issuecomment-286760126 `nth()` function should consume the iterator / generator to be less error-prone.

It should be noted that current implementation works differently for iterators and generators. (It finishes generators and stops iniside the iterators).

My proposal is to implement `Array.from( iterable )` instead of `for of` loop which consumes both iterators and generators.

**Comment by Reinmar** [comment]
Hm... you know what :D I proposed this but I now find it absolutely wrong. If that's an infinite collection (or just big) the `nth()` would crash or be unnecessarily slow.

**Comment by Reinmar** [comment]
You can close the ticket if now I make sense :P

**Comment by ma2ciek** [comment]
You're totally right. And it's impossible to finish the iterator without going through its all items. Hmm, so maybe I'll close this one and I'll add an issue to document the `nth()` function better :D
