### ISSUE TITLE
Implement utils/dom/isMatching

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#152]
As a polyfill for [`Element#matches()`](https://developer.mozilla.org/en/docs/Web/API/Element/matches).

I'm a bit unsure whether it'd be better to follow DOM's naming and have `dom/matches` or follow our convention and have `dom/isMatching`.

**Comment by Reinmar** [comment]
Required for: https://github.com/ckeditor/ckeditor5-ui/issues/214.

**Comment by oleq** [comment]
According to http://caniuse.com/#feat=matchesselector, Edge 15 implements this feature. I suppose it's a build for insiders because I couldn't get it from Windows Update, stuck at 14.14393. Perhaps all we need to do is wait. WDYT?

**Comment by Reinmar** [comment]
I have insider builds enabled and I'm stuck at 14.x as well ;<... So, let's wait.

**Comment by oleq** [comment]
As in https://github.com/ckeditor/ckeditor5-ui/issues/214#issuecomment-309741007, Edge 15 supports `domElement.matches()` and tests pass.
