### ISSUE TITLE
Rect constructor should accept a function as a source

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-utils#157]
A follow-up of https://github.com/ckeditor/ckeditor5-ui/issues/227 and https://github.com/ckeditor/ckeditor5-ui/issues/195.

**Comment by Reinmar** [comment]
Isn't rect immutable? Why is rect supposed to watch for changes? There's no explanation in neither of these tickets.

**Comment by oleq** [comment]
@Reinmar Please read the PR first.
