### ISSUE TITLE
Rect values should be parsed to int

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-utils#184]
We should avoid setting very accurate position values like `top: 103.4532px` `left: 94.278px` because browsers have some problems with that.

CT changes size and position:

![sep-20-2017 15-58-40](https://user-images.githubusercontent.com/1057056/30648544-92ef5ece-9e1e-11e7-8026-3eed9806974a.gif)

**Comment by Reinmar** [comment]
I think that rounding them to ints might not help in some cases. The problem here is that bolded letter is bigger than a normal one. So browser returns a bigger rect. If you'd round, that might not help if e.g. letter would change from `12.4px` to `13.1px`.

**Comment by Reinmar** [comment]
Anyway, not an issue that we need to work on for 1.0.0.

**Comment by oskarwrobel** [comment]
> The problem here is that bolded letter is bigger than a normal one.

Exactly, rect is bigger (different) so BPV should reposition without changing size of items inside. If the change is very little like 13.1 -> 13.8 repositioning is pointless.

**Comment by Reinmar** [comment]
So should it track the previous value and if the change was lower than some threshold it shouldn't move?

If any real user will report this, we could think about such solutions :D

**Comment by oskarwrobel** [comment]
After https://github.com/ckeditor/ckeditor5-ui/pull/498/commits/b33d5e97d96ef2fffdd44c7be66211163dcc6376 this issue does not make sense anymore.
