### ISSUE TITLE
Review how lodash is used by CKEditor 5

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#188]
Right now we include a lodash build in the repo (https://github.com/ckeditor/ckeditor5-utils/tree/master/src/lib/lodash).

* We were considering dropping it completely: https://github.com/ckeditor/ckeditor5/issues/361
* And discussing other matters related to how it affects CKEditor's size: https://github.com/ckeditor/ckeditor5/issues/435

Since we haven't refreshed Lodash's build for like something like a year now, and since it's not a good practice to include in this package anyway (cause it can't be reused if someone's already using Lodash), we should finally clean up this situation.

**Comment by Reinmar** [comment]
The easiest solution would be to remove lodash from this package and start importing it manually wherever it's needed:

```js
import at from 'lodash/at';
```

(or something like that – I never remember how importing CJS works with Webpack's ESM)

Lodash has zero dependencies so it won't slow down installation times.

However, there's been a long discussion in https://github.com/ckeditor/ckeditor5/issues/435 that Lodash (due to its extreme modularity) takes a lot of "space" in our bundles. We need to check whether this can be handled by Webpack in a better way (see https://github.com/ckeditor/ckeditor5/issues/475 and https://github.com/ckeditor/ckeditor5/issues/435#issuecomment-311779053). If not, I'd seriously consider dropping lodash cause we really use just a couple of functions:

```js
[ 'arrayUtils',
  'clone',
  'cloneDeepWith',
  'debounce',
  'extend',
  'isArray',
  'isElement',
  'isEqual',
  'isEqualWith',
  'isFunction',
  'isNative',
  'isObject',
  'isPlainObject',
  'isString',
  'last' ]
```

**Comment by oskarwrobel** [comment]
Latest Lodash exported as ES modules is available on npm https://www.npmjs.com/package/lodash-es.

**Comment by pjasiun** [comment]
See https://github.com/ckeditor/ckeditor5-utils/issues/251.

**Comment by Reinmar** [comment]
I don't think we'll want to spend more time on this so let it be like it is.
