### ISSUE TITLE
Remove `on`, `once` and `off` methods from `EmitterMixin`

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-utils#191]
As @pjasiun noted the usage of `EmitterMixin` methods is ambiguous.

We have two methods for registering listener (`on` and `listenTo`) and two methods for removing listeners from emitter ( `off` and `stopListening`).

After refactoring `on`/`off` are only shorthand methods for their counter parts:
```js
this.on( 'event', () => {});
// is the same as
this.listenTo( this, 'event', () => {});

// the same for
this.off( 'event' );
// is a shorthand for
this.stopListening( this, 'event' );
```

This can lead to confusion on when to use which method.

Proposed solution is to remove `on`, `off` and `once` methods and use only `listenTo`/`stopListening` ones.

The only problem is that `on`/`off` methods provides nice shorthands which is very usable in tests and when registering event listener on `this` or given emitter.

Second proposition is to make `emitter` parameter optional.

```js
this.listenTo( this, 'event', () => {} );
// will be this same as:
this.listenTo( 'event', () => {} );
```

The `stopListening` method will behave as before so there will be no `off` shorthand:
```js
// Previous off:
this.off();
// after change must be called explicitly with this
this.stopListening( this );
// while below will remove all registered events for all emitters.
this.stopListening();
```

**Comment by pjasiun** [comment]
Or maybe, if we like `on` that much we can rename `listenTo` to `on`:
```js
this.on( foo, 'event', () => {} );
this.on( 'event', () => {} ); // this as a default value

this.once( 'event', () => {} );

this.off( foo, 'event' );
this.off( 'event' );
```

WDYT?

**Comment by jodator** [comment]
Yeah definitely only one should stay to avoid confusion. I think that I like shorter solution more. Also I think that `on` is more common then `listenTo` (just a feeling no stats). The only problem I have is with `stopListening` and `off` semantics as I think that those methods make a bit more now.

```js
// 1: remove given `callback` for `event` from `emitter`
self.stopListening( emitter, 'event', callback );
self.off( emitter, 'event', callback );

// 2: remove all `self` `callback`s for `event` from `emitter`
self.stopListening( emitter, 'event' );
self.off( emitter, 'event' );

// 3: remove all `self` `callbacks` for all `event`s from `emitter`
self.stopListening( emitter );
self.off( emitter );

// 4: remove single `callback` for `event from `self`
self.stopListening( 'event', callback );
self.off( 'event', callback );

// 5:  remove all `self` `callback`s for `event` from `self`
self.stopListening( 'event' );
self.off( 'event' );

// 6:  remove all `self` `callbacks` from `self`
self.stopListening();
self.off();
```

Now looking at this I don't have clear statement how to call them. The main problem with this API is mixing `Observer` and `Emitter` into one.

Given that I see that:
- `on` does two things:
   1. register `callback` for `event` on `emitter`
   2. register `emitter` to `listenigTo` object for `event` on `self`
- `off` does also:
    1. remove `callbacks` from `emitter`
    2. deregisters `emitters` from `listeningTo` object from `self`

The `listeningTo` is used to have nice method to remove all own listeners:
`this.stopListening()` should detach from all `emitter`s.

**Comment by fredck** [comment]
Note that this is not something invented by us. Both `on` and `listenTo` have been created based on the good and old Backbone implementation (see [on](http://backbonejs.org/#Events-on) and [listenTo](http://backbonejs.org/#Events-listenTo)).

They definitely have different purposes and it is all related to the destruction workflow, I assume, where cleanup is made either by the listener or the emitter, depending on the case.

Anyway, just adding these bits here, to be sure that this hasn't been unsaid.

**Comment by Reinmar** [comment]
I'd leave what we have now (or rather – what we'll have after closing the current PRs) because I don't have strong feelings about this. Let's live with this for a while and see if we really need to change anything. This is a piece of code which will be touched by the community so we'll see if there's any confusion.

**Comment by Reinmar** [comment]
It seems that everyone forgot about this so I'm closing this ticket.
