### ISSUE TITLE
There should be a way to check CKEditorError with parameters

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#2]
Moved from https://github.com/ckeditor/ckeditor5-core/issues/68

**Comment by Reinmar** [comment]
Turns out this will be needed because of compatibility with ES5: https://github.com/ckeditor/ckeditor5-dev-compiler/issues/18#issuecomment-240718336.

**Comment by Reinmar** [comment]
We've been originally thinking about extending Chai by adding `expect().to.throwCKEditorError()`. I'm a bit afraid of doing this, but otherwise, we'll not be able to use this function at all.

I was also thinking about adding `isCKEditorError( err, [ msgPattern ] )` function (and exporting it) to the `utils/ckeditorerror` module. This function will then be usable in the dev code. The Chai's extension would of course use this function.

**Comment by maxbarnas** [comment]
I've added static method `isCKEditorMethod` to `utils/ckeditorerror`. This implementation is still not valid in code transpiled to ES5.

**Comment by Reinmar** [comment]
> I've added static method isCKEditorMethod to utils/ckeditorerror. This implementation is still not valid in code transpiled to ES5.

Could you put it on review?

**Comment by maxbarnas** [comment]
I set this as invalid because of problems with Chai extension in bundles. We'll use Babel plugin, that allows to extend builtin types - this will make `instanceof` usable again.
