### ISSUE TITLE
EmitterMixin namespaces

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-utils#200]
How this feature should behave? I have some troubles with getting requirements and tests namespaced events.

1. How deep should be namespaces 1) `foo:bar` only or 2) `u:n:l:i:m:i:t:e:d` (you see what I did there)?
2. How should `stopListening()` behave on namespaces (especially deep one)? Should it stop listening also child events?

Ad. 1. AFAICS the `listenTo()` part allows to assign any depth and it works:

```js
listener.listenTo( emitter, 'foo', ( evt, msg ) => console.log( msg ) );

emitter.fire( 'foo:bar:baz:abc', 'it works' );
// would log "it works"
```

So the we register listener for any `foo[:*]` event.

Ad. 2. Now the `stopListening()` part behave a bit differently.

```js
listener.listenTo( emitter, 'foo:bar:baz:abc', (evt, msg) => console.log( msg ) );
listener.stopListening( emitter, 'foo' );

emitter.fire( 'foo:bar:baz:abc', 'abc' );
// will log 'abc'
```

It's ether a feature (should be documented) or a bug (should be fixed).

**Comment by pjasiun** [comment]
> 1. How deep should be namespaces 1) `foo:bar` only or 2) `u:n:l:i:m:i:t:e:d` (you see what I did there)?

As you already notice, it should be unlimited, we already use 3rd level.

> 2. How should `stopListening()` behave on namespaces (especially deep one)? Should it stop listening also child events?

I think that if you want to stop listening centrain event, you should use the same event name you put in `listenTo`. So if you listen to `foo:bar` you need to stop listening `foo:bar`. There might be a separate listener on `foo`. If you need to detach the whole group of listener you can create new `observable` object, set all listeners on it and remove them using `observable.stopListening()`.

**Comment by jodator** [comment]
@pjasiun other question as I have hard feelings about that namespaced events as this might be unintended side effect:

```js
emitter.once( 'foo', spy );

emitter.fire( 'foo:bar' );
emitter.fire( 'foo:bar' );
emitter.fire( 'foo:bar' );

// will call spy indefinitely
```
(also asked here: https://github.com/ckeditor/ckeditor5-utils/pull/190#event-1345015231.

**Comment by Reinmar** [comment]
I guess we support this already. Or I misunderstood this ticket.
