### ISSUE TITLE
Regression: It should be possible to skip some elements when binding collections

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-utils#215]
Introduced here: https://github.com/ckeditor/ckeditor5-ui/issues/92.

```javascript
collectionA.bindTo( collectionB ).using( item => {
    if ( item.hidden ) {
        return null;
    }

    return new Something( item );
} );
```

**Comment by Reinmar** [comment]
> Introduced here: ckeditor/ckeditor5-ui#92.

But it's an open ticket. Did it have some PRs?

**Comment by oskarwrobel** [comment]
Didn't notice it's open :). AFAIK there is no PRs for the https://github.com/ckeditor/ckeditor5-ui/issues/92. I'm closing this ticket as a DUP.

**Comment by oskarwrobel** [comment]
But... This ticket is in the right repo :)

**Comment by oskarwrobel** [comment]
This PR https://github.com/ckeditor/ckeditor5-utils/pull/216 will close both (ui and utils) tickets.
