### ISSUE TITLE
Extract Listener from Emitter

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-utils#23]
Inspired by https://github.com/ckeditor/ckeditor5-design/issues/142.

Shouldn't we split `Emitter` and `Listener`? `listenTo` and `stopListening` does not sound like `Emitter` methods. Also it is strange that I need to implement something called `Emitter` only to listen to events. There could be also a function `createListener` which... creates a listener.

**Comment by Reinmar** [comment]
Sounds nice.

I would also consider finding a shorter name than `listenTo()`... Maybe simply `listen()`?

**Comment by oskarwrobel** [comment]
I agree that methods about listening don't sound like emitter methods but on the other hand splitting emitter object could be a little confusing for developers. Every implementation of EventEmitter I know (include node.js https://nodejs.org/api/events.html) contains both listen and emit methods in the same object.

**Comment by Reinmar** [comment]
Good point. I'm not sure as well now... this seems like two separate things, emitting and observing, but OTOH I've never seen them split as well. WDYT, @pjasiun?

**Comment by pjasiun** [comment]
Agree that if developers used to have this classes together we should not try to reinvent the wheel. OTOH we could consider having `Listener` as a base class of every class we use, and `stopListening` on `destroy` by default. But this is another topic. We could keep `Emitter` the way it is, for now.

**Comment by Reinmar** [comment]
> OTOH we could consider having Listener as a base class of every class we use, and stopListening on destroy by default. But this is another topic.

I'm definitely against that. First of all, in 90% of classes we don't need this functionality. Second, we had base class and... well, we don't, cause see 1) :D. Third, why would a listener be a base class? That should be a separate class anyway.

Since we all agree that splitting is a bit an overreaction to how we started using it, I'm closing this issue as invalid.
