### ISSUE TITLE
Coverage not 100% due to 'translation-service.js'

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-utils#237]
One code branch is not covered in `translation-service.js`:

![image](https://user-images.githubusercontent.com/1061942/38808690-55735b84-4181-11e8-9ca7-70d856350906.png)

**Comment by ma2ciek** [comment]
Would be better to move that code into a function and invoke it from `add()` and `translate()` functions or just ignore the else branch from CC?

**Comment by Reinmar** [comment]
Hm... let's ignore the else branch.
