### ISSUE TITLE
Rename keyboard.keyNames to keyboard.keyCodes

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-utils#24]
This collection contains key codes. I was unsure if I should compare `data.keyCode` with `keyNames.arrowleft`. `data.keyCode == keyCodes.arrowleft` looks better.

**Comment by Reinmar** [comment]
You wasn't meant to compare any of it (use `getCode()`)... That object was exposed mainly to be extended, not to be used to get codes, but you're right that, if you know the name precisely, you can use it directly.

Anyway, you're right that its a collection of key codes.
