### ISSUE TITLE
focusTracker event "change:isFocused" gets fired using imageupload plugin in chrome

### ISSUE THREAD

**Issue by MBERoxit** [ckeditor/ckeditor5-utils#275]
I'm using a custom inline editor. 
The following code doesnt work as expected when using the imageupload plugin in the toolbar

```
focusTracker.on('change:isFocused', (evt, name, isFocused) => {
	if (!isFocused) {
		alert("should not happen using the imageupload plugin via the toolbar");
	}
});
```
The alert box isnt triggered in FireFox (which is good in my opinion), but in Chrome it is.

I want to do some resource cleaning up in my code after the editor is losing the focus, but I cannot do this in chrome because of this issue

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
I confirm it (also in Safari) but I'm not sure this is an issue. It looks more like a browser quirk and quite likely there's nothing we can do about it.

OTOH, when I checked

```js
editor.ui.focusTracker.on('change:isFocused', (evt, name, isFocused) => {
	if (!isFocused) {
		console.log( window.document.activeElement === editor.ui.view.editable.element );
	}
});
```

it indicates that editor editable remains an active element in this situation. I guess you could use this knowledge to **not** execute your clean–up logic in this case. Let us know if it helps.

**Comment by MBERoxit** [comment]
Thanks Oleq! This solves my problem :)
