### ISSUE TITLE
Observable Collection#length property.

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-utils#284]
I need to display in UI a total number of items in a collection (it's not the first time). Unfortunately, collection `#length` property is not observable (it's a getter) so I can't simply bind it with UI. I need to create an observable property and listen to the collection `add` and `remove` events and update the observable.

I propose to change `Collection#length` to observable.

My only concern is that collection is used many times across the editor and this will increase the number of callbacks, so maybe it's not worth to create such a generic solution to cover only a few cases?

WDYT?

**Comment by oskarwrobel** [comment]
> this will increase the number of callbacks

It depends on implementation. My first idea was to listen to the `add` and `remove` event and update observable, but it can be done in the other way. Just increment/decrement observable at the end of add and remove methods.

**Comment by pjasiun** [comment]
I think it is a good idea. It should not be any performance problem, should be backward compatible and it might be useful in many cases.

**Comment by oskarwrobel** [comment]
https://github.com/ckeditor/ckeditor5-utils/pull/285#issuecomment-489654713
