### ISSUE TITLE
Create toJSON/fromJSON utility methods for Map

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-utils#35]
Some ES6 standard built-in objects are serialized by `JSON.stringify` to empty object.

As for now the only needed type is Map.

**Comment by jodator** [comment]
Ugh.. after reading some docs it is probably safe to assume that `map.entries()` or
```js
let map = new Map();
map.set( 'a', 'b' );
let mapForSerialization = [ ...map ];
let otherMapForSerialization = map.entries();
```
will do better then adding helper function.

**Comment by Reinmar** [comment]
That's not going to work:

```js
JSON.stringify( new Map( [ ['a', 1], ['b', 2] ] ).entries() )
```

This will:

```js
JSON.stringify( [ ...new Map( [ ['a', 1], ['b', 2] ] ) ] )
```

So the latter is fine (except that maps are usually fine to be represented as objects). But such util function which does this would be helpful. I mean – a function which you can pass as second arg for `JSON.stringify()` which replaces every encountered Set and Map with an array/object.

**Comment by Reinmar** [comment]
The question is whether we need to serialize deep structures where maps or sets can be one of deeper nested properties. If not, then obviously you can simply do `Array.from( myMap )` and you'll be fine.
