### ISSUE TITLE
Observable#unbind: unbinding attribute which is not bound throws ambiguous error

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#5]
Moved from https://github.com/ckeditor/ckeditor5-core/issues/153

``` js
A.bind( 'x' ).to( B, 'a' );
A.unbind( 'totallyNotBoundToAnythingOrEvenNotExistingInA' );
```

**Actual**: `TypeError: Cannot read property 'to' of undefined`

**Expected**: A meaningful error.

**Comment by jodator** [comment]
I've just stumbled upon this. Still an issue... as in my feature I'm binding/unbinding stuff and there is no way to check if a binding already exists (AFAIK).

**Comment by oleq** [comment]
IMO unbinding a non-existent attribute should not throw an error. Since `o.unbind()` does not throw, neither `o.unbind( 'nonexistent' )` should throw.

**Comment by oleq** [comment]
> Still an issue... as in my feature I'm binding/unbinding stuff and there is no way to check if a binding already exists

Just to be clear, this sounds like another problem. If you meant double bindings like
```js
A.bind( 'x' ).to( B, 'a' );
A.bind( 'x' ).to( B, 'a' ); // -> this one throws
```

this should be a separate issue. Perhaps we should not throw in such situation.

**Comment by jodator** [comment]
@oleq I'm describing problem from you first comment:

```js
const a = new ObservableClass();
a.unbind( 'foo' ); // whoopsie :(
```

On the second I don't have an opinion... maybe it is OK to throw as we allow only one binding per attribute.

**Comment by jodator** [comment]
OK. I've created a rather simple fix for that issue only.
