### ISSUE TITLE
EmitterMixin: introduce worded priority levels.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-utils#55]
`EmitterMixin` should take constants as a way to describe callback priority. I propose 5 levels of priority:
* `highest`
* `high`
* `normal`
* `low`
* `lowest`

Callbacks with higher priority will be fired before callbacks with lower priority, so callback added with 'very_high' priority will be called before callback with 'normal' priority. When two callbacks have same priority level, they are fired in the order of adding.

I expect core features to mostly use `highest`, `normal` and `lowest`.  If needs be, we might introduce `very_high` and `very_low` priority. However right now most scripts do not use priority at all, so I belive that 5 levels will be enough for long time.

For debugging and testing purposes, an object with constants-to-numbers mapping will be exported, like discussed here: https://github.com/ckeditor/ckeditor5-utils/issues/8#issuecomment-236164721. I also thought about different solutions, but this one is simplest. My only worry is that people will use it also outside of tests, even if we write in documentation that they should not. I haven't thought how to solve this issue, though. I had some ideas but each of them is lacking. Still, I think it's important to have flexibility in priority setting for test purposes.

**Comment by scofalik** [comment]
Another solution is to introduce named callbacks.

When adding callback to an event, you would have a possibility to give it a name (name would be a `String`). I know that you could just store callback in a variable but it is akward for few reasons. Name would be an optional parameter, global for whole editor (not attached to just one emitter).

Then you could use priority like `'after:namedCallback'` or `'before:namedCallback'` and it would evaluate the value, just like it does with priority `'high'`. If callback name is not found, priority `'normal'` would be used.

Yes, you have to look-up what is the callback name if you want to hook-up after or before it. Yes, it is not perfect, someone can hook-up between original callback and `'after'`/`'before'` callback. However, these also exist without this functionallity.

What we gain?
* We don't have to pretend that `EmitterMixin` does not accept `Number` as priority and we do not have to export silly functions/objects that converts strings to priority numbers.
* We have nice utility for data pipelines. 

What do we lose?
* Bigger complexity of `EmitterMixin` methods. I could squelch `ctx`, `priority` and `name` parameters to one parameter `options`, though.

**Comment by pjasiun** [comment]
> one added later will be fired as first.

It is wrong. If I add:
```
obj.on( 'evt', () => console.log( 'foo' ) );
obj.on( 'evt', () => console.log( 'bar' ) );

obj.fire( 'evt' );
```

I expect to see:
```
foo
bar
```

Otherwise, I am not able to easily split my code into multiple listeners.

**Comment by scofalik** [comment]
I already fixed that part.

**Comment by pjasiun** [comment]
> Another solution is to introduce named callbacks.

The whole point of using event is that listeners are independent, know nothing about each other. 

Assume there are listeners `A` and `B` in the system, `B` is before `A`. You want to add listener `C` which will be always before `A` and `B`, so you add it "before `B`". Then, the plugin which introduces listener `B` disappear. How do you know that now `C` should be before `A`?
Or another case: you want to add `X` before `B`, but after `C`, how you define it?

I think it will bring more problems then solutions.

**Comment by pjasiun** [comment]
> My only worry is that people will use it also outside of tests, even if we write in documentation that they should not.

There are 1000 ways people can use one code in the wrong way. This is only one of them ;)
