### ISSUE TITLE
Compatibility issues in tests

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-utils#66]
Related: ckeditor/ckeditor5#312.

**Comment by maxbarnas** [comment]
Test in https://github.com/ckeditor/ckeditor5-utils/blob/master/tests/unicode.js#L11 fails because of regexp test returning `false` in https://github.com/ckeditor/ckeditor5-utils/blob/master/src/unicode.js#L29. 

I noticed two things so far:
- using RegExp constructor instead of inline regex helps a little,
- Babelified code of the the test is mangled,
- the same code from `isSurrogateHalf` in Safari's console works fine.

I would be happy to use RegExp constructor and call it a day, but when using it a lot of other tests fail. This needs further checking.

**Comment by Reinmar** [comment]
:/ We should report an issue to Babel after confirming that this is really a bug.

**Comment by Reinmar** [comment]
Could you handle reporting it to Babel?

**Comment by maxbarnas** [comment]
@Reinmar Yep, I will report it.

**Comment by maxbarnas** [comment]
Seems it is already reported: https://github.com/babel/babel/issues/3826.
