### ISSUE TITLE
Improve getEnvKeystrokeText so it handles also Shift and Alt

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#75]
After https://github.com/ckeditor/ckeditor5-utils/issues/74 is done we need to improve this function so it handles more keys, and depending on the outcome of #74, a different order of modifiers.

**Comment by oleq** [comment]
So you'd expect `Alt+0` to become `⌥0`  and `SHIFT+X` to become `⇧X` in OSX?

**Comment by Reinmar** [comment]
Looking at our tests this is already done:

```js

			it( 'work for multiple modifiers', () => {
				expect( getEnvKeystrokeText( 'CTRL+SHIFT+X' ) ).to.equal( '⌘⇧X' );
				expect( getEnvKeystrokeText( 'ALT+SHIFT+X' ) ).to.equal( '⌥⇧X' );
			} );
```
