### ISSUE TITLE
Merge EmiterMixins#on's ctx and prior args into options object

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#76]
Having them separately is a problem for us because we want to add another option there in the DomEmitterMixin object – the `useCapture`.

```js
on( evtName, callback, options )
```

**Comment by scofalik** [comment]
Can we just get rid off context parameter? I thought we removed it already.

**Comment by scofalik** [comment]
Sorry, wrong button.

**Comment by Reinmar** [comment]
If it isn't used anywhere, then we could. But still we should make the last arg an "options" object, because we need to add more stuff there.
